### PR TITLE
Add automatic yt-dlp update check

### PR DESCRIPTION
**Pull request by nbtin**
Hi Lasith,

I've recently downloaded your plugin on Flow Launcher. This plugin is interesting. I love it! ❤️

After scrolling your GitHub repo, I found that your plugin is based on **yt-dlp** (actually a `.exe` file in your repo). I want to know what you intend to do if **yt-dlp** has its own updated version. Will you update the `.exe` file manually? I noticed that by the time I made this pull request, they had a newer version of it (2024.08.01) but your file is still 2024.07.25.

I suggest you fetch and download the `yt-dlp.exe` file directly from their repo ([https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp.exe](https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp.exe)). And this process doesn't need to be conducted every time the app is triggered, I recommend you to set an interval (eg: 3 days, 1 week...) to check it automatically.

Have a good day!

### CODE REVIEW

**Comment by z1nc0r3** [comment]
Hi @nbtin 

Thanks for the idea and the PR 🙌
However, I did some research and found that there is an [Update option](https://github.com/yt-dlp/yt-dlp#general-options) that we can pass as a parameter to the executable.

simply saying, that `-U` will update the executable itself before downloading the video.
`yt-dlp -U [other options]`

**Comment by nbtin** [comment]
Ohh, I didn't realize that, hehe. Thanks for letting me know, keep up the good work @z1nc0r3 !

**Review by z1nc0r3 — COMMENTED** [review]
I was thinking about just adding `-U` flag to the current command variable.

`command = f"yt-dlp -f {format_id}+ba {url} -P ~/Downloads/AnyDownloader -U --windows-filenames --quiet --progress --no-mtime --force-overwrites --no-part"`

wdyt?

**Comment by nbtin** [comment]
Totally get it! 😸

It's just different perspectives on the same issue. Adding the `-U` flag into the current command variable is a good way to simplify the code 👍. However, I just wonder if it needs to wait a bit for checking updates every time users want to download a video. I think it's a trade-off here.

In my opinion, nobody likes surprise updates when they're just trying to grab a funny cat video 😂. So, I think setting time intervals would make things less 'Windows Update-y', and users only update once a day (after a while)...

**Review by z1nc0r3 — CHANGES_REQUESTED** [review]
Ah right, got the idea 😉

Anyway, I have some suggestions for making the code as simple as possible.

- One thing noticed is here it seems to open a separate terminal for the update process, which may conflict with the actual download terminal. Because both trying to use the same executable file.
- So, maybe we can move the checking for the update function call to the _download_ function, just after the command variable. And append the `-U` flag to the already existing command.
- And the last thing is the logic behind the getting last day. I think we can use something like `os.path.getmtime(file_path)` to get the last modified date of the _.exe_ file and compare it with today and take a decision.

Need your suggestions on this. And sorry to ask for lots of reviews 😅

**Comment by nbtin** [comment]
A LOT OF good reviews help us code better =)) I'm okay with that, hehe. 
Anyway, your suggestions are lit :)) My code is quite complicated 😅. Maybe I'm overthinking 😆. 
I have changed the code a bit, take a look bro @z1nc0r3 😷

**Review by z1nc0r3 — APPROVED** [review]
Looks Awesome! Thanks 🙌

**Pull request merged**
